version: "3"
services:
  web:
    container_name: todo-app-remake
    build: .
    env_file:
      - .env
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - todo_app_network
    ports:
      - 8084:8084

  db:
    container_name: db-todo-app
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - 5438:5432
    volumes:
      - ./todo_schema.sql:/docker-entrypoint-initdb.d/todo_schema.sql
      - dbdata:/var/lib/postgresql/data
    networks:
      - todo_app_network

volumes:
  dbdata:

networks:
  todo_app_network:
    driver: bridge