version: "3"
services:
  web:
    container_name: todo-app-remake
    build: 
      context: .
    env_file:
      - .env
    restart: always
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - todo_app_network
    ports:
      - 8084:8080

  db:
    container_name: db-todo-app
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - 5436:5432
    networks:
      - todo_app_network

networks:
  todo_app_network:
    driver: bridge